services:
  db:
    image: postgres:16
    container_name: garangbi-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garangbi
    volumes:
      - garangbi-data:/var/lib/postgresql/data

volumes:
  garangbi-data: